services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - "mynet"

  database:
    platform: "linux/x86_64"
    image: "mysql:latest"
    ports:
      - "10000:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "snippetbox"
    volumes:
      - db-data:/var/lib/mysql
networks:
  mynet:
    driver: bridge

volumes:
  db-data:

